<a href="https://colab.research.google.com/github/adityarathore063/Machine-learning-and-AI/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Numpy in Python**

In [26]:
import numpy as np
import math as m

In [2]:
demo = [1,2,3]
np.array(demo)

array([1, 2, 3])

In [3]:
demo2 = [1,2,3,"xyz"]
np.array(demo2)

array(['1', '2', '3', 'xyz'], dtype='<U21')

In [9]:
# Some numpy function

x = np.zeros(5)
y = np.zeros(5,int)
print(x)
print(y)

print(x.dtype)
print(y.dtype)

a = np.ones(5)
b = np.ones(5,int)
print(a)
print(b)

[0. 0. 0. 0. 0.]
[0 0 0 0 0]
float64
int64
[1. 1. 1. 1. 1.]
[1 1 1 1 1]


In [15]:
arr = np.ones((2,3),int)
arr[1][1] = 5
print(arr)
print(arr[1][1])
print("Shape is ",arr.shape)

[[1 1 1]
 [1 5 1]]
5
Shape is  (2, 3)


In [13]:
np.ones((2,3,4),int)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [17]:
arr2 = np.ones(6,int)
arr2[3] = 5
print(arr2[3:6])

[5 1 1]


In [18]:
arr3 = np.array([[1,2,3],[4,5,6],[6,7,8]])
print(arr3[1:3])
print(arr3[:,1])


[[4 5 6]
 [6 7 8]]
[2 5 7]


In [24]:
c = np.array([1,2,3])
d = np.array([7,5,6])

c = c+10
print(c)
print(c+d)


[11 12 13]
[18 17 19]


In [25]:
print(d.mean())
print(d.sum())

6.0
18


In [28]:
# Findind distance between two points p1 and p2
p1 = np.array([2,2,2])
p2 = np.array([1,1,1])

val = ((p1 - p2)**2).sum()

print(m.sqrt(val))

#dot product
print(p1.dot(p2))

1.7320508075688772
6
